; /etc/asterisk/extensions.conf
[general]
static=yes
writeprotect=no

[from-external]
exten => _X.,1,NoOp(Incoming Call to ${EXTEN} from ${CALLERID(num)})
 same => n,Answer()
 same => n,Stasis(dograh)
 same => n,Hangup()

[from-vobiz]
exten => _X.,1,NoOp(Incoming Call to ${EXTEN} from ${CALLERID(num)})
 same => n,Answer()
 same => n,Stasis(dograh)
 same => n,Hangup()
